matlab2tikz(figname,...
	'height','\figheight','width','\figwidth',...
	'parseStrings',false,...
    'dataPath', './fig','relativeDataPath','./fig','imagesAsPng', false,...
	'extraAxisOptions',{'ylabel near ticks',...
                        'xlabel style={font=\normalsize},'...
                       'ylabel style={font=\normalsize},'},...
    'showInfo', false)